apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: '${{ github.event.repository.name }}'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "2"
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containers:
      - image: '${{secrets.GCP_ARTIFACT_REGISTRY}}/${{ github.event.repository.name }}:latest'
        resources:
          limits:
            cpu: '2'
            memory: '32Gi'
            gpu: '1'
            gpu-type: 'nvidia-14'
            maxInstances: '3'